name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      env:
        # The hostname used to communicate with the Redis service container
        REDIS_URL: 'redis://redis:6379/'
        RUST_LOG: 'info'
    - name: Build
      run: cargo build --verbose
